<a href="https://colab.research.google.com/github/avinashronanki/pytorch/blob/master/pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 
x = torch.rand(3)
print(x)

In [ ]:
torch.cuda.is_available().  # to check if gpu is connected or not 

In [ ]:
empty = torch.empty(3) # un intialized memory /data 
print(empty)

In [ ]:
zero = torch.zeros(3)
print(zero)

In [ ]:
empty + one

In [ ]:
one = torch.ones(3)
print(one)

create 2d 3d and 4d tensor 

In [ ]:
twod = torch.rand(2,2)
threed = torch.rand(2,2,2)
fourd = torch.rand(2,2,2,2)

In [ ]:
c  = torch.ones(2,2, dtype =torch.float) # mention date type 

list 

In [ ]:
l = torch.ones([1,2])

Adding two tensors 

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z= x+y   
print(z)

z = torch.add(x,y) # add function 


tensor([[0.8325, 1.3713],
        [0.8632, 0.8652]])


In [ ]:
print(y)

tensor([[0.6337, 0.7274],
        [0.4152, 0.3477]])


modify the variable with addition 

In [ ]:
y.add_(x)
print(y)

tensor([[0.8325, 1.3713],
        [0.8632, 0.8652]])


substraction 

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z= x-y   
print(z)

z = torch.sub(x,y) # substraction function 

divison 

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z= x/ y   
print(z)

z = torch.div(x,y) # division  function 

Slice

In [ ]:
a = torch.rand(5,4)

In [ ]:
print(a)

tensor([[0.9725, 0.8286, 0.1985, 0.6716],
        [0.5158, 0.3561, 0.6893, 0.1104],
        [0.8168, 0.3879, 0.8921, 0.6888],
        [0.7019, 0.3297, 0.7578, 0.1883],
        [0.5933, 0.2272, 0.2099, 0.8052]])


In [ ]:
print(a[1:3,:])

In [ ]:
print(a[[2,4],:])

In [ ]:
a[1,1] # taking a specific postion 

tensor(0.3561)

In [ ]:
a[1,1].item()   # if you need the value of the tensor 

0.3561347723007202

REshape 

In [ ]:
r = torch.rand(6,6)
print (r)
y = r.view(36) # in a single list 
print(y)

tensor([[0.9520, 0.2428, 0.4987, 0.7993, 0.8776, 0.7078],
        [0.9136, 0.2007, 0.8112, 0.7529, 0.3412, 0.7893],
        [0.9817, 0.1569, 0.0114, 0.0199, 0.5911, 0.3896],
        [0.7242, 0.4373, 0.9833, 0.1772, 0.8281, 0.1766],
        [0.5861, 0.9514, 0.2313, 0.0517, 0.6457, 0.7085],
        [0.0889, 0.1592, 0.9855, 0.2104, 0.8430, 0.4124]])
tensor([0.9520, 0.2428, 0.4987, 0.7993, 0.8776, 0.7078, 0.9136, 0.2007, 0.8112,
        0.7529, 0.3412, 0.7893, 0.9817, 0.1569, 0.0114, 0.0199, 0.5911, 0.3896,
        0.7242, 0.4373, 0.9833, 0.1772, 0.8281, 0.1766, 0.5861, 0.9514, 0.2313,
        0.0517, 0.6457, 0.7085, 0.0889, 0.1592, 0.9855, 0.2104, 0.8430, 0.4124])


In [ ]:
# convert into 8 column metric 

y = r.view(-1, 9)
print(y)

In [ ]:
z = r.view(2, -1)
print(z.size())

In [ ]:
z.view(-1)

numpy array 

In [ ]:
import numpy as np
 
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
# numpy to tensor 

n = np.ones(5)
print(n)
t = torch.from_numpy(n)
print(t)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
n += 1
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


cuda 

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device= device)
  y = torch.ones(5)
  y = y.to(device) # converting into cuda 
  z= x+y 

  print(z)


tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [ ]:
# moving it back to cpu version 
z= z.to("cpu") # important 


Gradients calculation with Autogred 

In [ ]:
g = torch.ones(5, requires_grad=True)
print(g)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [ ]:
x = torch.rand(3,3, requires_grad=True)
print(x)

y = x+2
print (y) #  grad_fn=<AddBackward0> 

tensor([[0.4301, 0.7209, 0.7149],
        [0.2627, 0.6174, 0.3840],
        [0.8414, 0.7427, 0.7175]], requires_grad=True)
tensor([[2.4301, 2.7209, 2.7149],
        [2.2627, 2.6174, 2.3840],
        [2.8414, 2.7427, 2.7175]], grad_fn=<AddBackward0>)


In [ ]:
z = y*y*2

print (z) #grad_fn=<MulBackward0>)

tensor([[11.8104, 14.8063, 14.7417],
        [10.2396, 13.7019, 11.3670],
        [16.1467, 15.0444, 14.7700]], grad_fn=<MulBackward0>)


In [ ]:
z = z.mean()
print(z) # grad_fn=<MeanBackward0>)

tensor(13.6253, grad_fn=<MeanBackward0>)


In [ ]:
# backward pass 
z.backward() # dz/dx
print (x.grad)

tensor([[1.0800, 1.2093, 1.2066],
        [1.0056, 1.1633, 1.0596],
        [1.2628, 1.2190, 1.2078]])


In [ ]:
# with out disturbing the gradents perfroming some operation on x 
x = torch.rand(3, requires_grad=True)
print(x)
x.requires_grad(False)
x.detach()
with torch.no_grad()

y = X+2 
print (y)

Neural network with weights 

In [ ]:
import torch 

weights = torch.ones(4, requires_grad=True)
print(weights)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()
  print(model_output)

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)


optimizer SGD

In [ ]:
import torch 

weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr= 0.01)
optimizer.step()
optimizer.zero_grad()

Backpropagation 
1. forward pass (loss)
2.local gradients 
3.backword propagation loss 

In [ ]:
# chain rule 
# computational graph 

#linear regression 


import torch 

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w= torch.tensor(1.0, requires_grad=True)

#forword pass and compute loss

y_hat = w * x
loss =(y_hat - y)**2

print(loss)

#backword pass 
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


Gradient Descent With Autograd and Backpropagation 



In [ ]:
prediction : pytoch model 
GD : Auto grad 
Loss Computation : loss function 
parameter : optimizer 

In [ ]:
#linear Regression 

X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)
w=0.0


#model prediction 
def forward(x):
  return w * x


#loss =MSE
def loss(y, y_predicted):
  return ((y_predicted - y)**2).mean()


#gardient
#MSE = 1/N * (w*x -y) **2
#d/dw =1/N 2x (w*x -y)
def gradient( x, y, y_predicted):
  return np.dot(2*x, y_predicted -y).mean()

print("Prediction before training: f(5) = {forward(5):.3f}")

#training
learning_rate = 0.01
n_iters = 20


for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = forward(X)

  #loss
  l = loss( Y, y_pred)


  #gradients
  dw = gradient( X, Y, y_pred)


 #update weights
  w -=learning_rate * dw

  if epoch % 2 == 0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss {l:.8f}')

print(f"Prediction after training: f(5) = {forward(5):.3f}")

Liner regression with pytorch

In [ ]:
import torch
import torch.nn as nn



#needs an input size and output size as features .. need to be a 2D array .. no of rows is the no of samples so change the shape of X & Y 
X = torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
Y = torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)

X_test = torch.tensor([5], dtype=torch.float32) 


n_samples, n_features =X.shape
print(n_samples, n_features)

#remove the weights since the function nn.linear() contains the weights inbuilt linear regression function by pytorch
#model prediction 

input_size = n_features
output_size = n_features

# foward == model 

# weigths become models.paramters  // used by DeClare
#linear model with random weigths will be created


#creating a custom model ( where many layers can be added for fine tuning)
class LinearRegression(nn.Module):
  def __init__(self, input_dim, output_dim):
      super(LinearRegression, self).__init__()   # super constructer
      #define layers here 
      self.lin = nn.Linear(input_dim, output_dim)


  def forward(self, x):
     return self.lin(x)

model = LinearRegression(input_size, output_size)

print("Prediction before training: f(5) = {model(X_test).item():.3f}")

# remove the loss function and add the built in function MSELoss()

#training
learning_rate = 0.01
n_iters = 100
loss = nn.MSELoss()


# acts as a back propogation
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = model(X)

  #loss
  l = loss( Y, y_pred)


  #gradients = backward pass
  l.backward() #loss with respect to w --> dl/dw
  
  # dw = gradient( X, Y, y_pred)


  #update weights
  optimizer.step()


  #zero gradients
  optimizer.zero_grad()
  if epoch % 10 == 0:
    # wanrt to print so unpack them 
    [w, b] = model.parameters()
    print(f'epoch {epoch+1}: w = {w[0][0].item():.3f}, loss {l:.8f}')

print(f"Prediction after training: f(5) = {model(X_test).item():.3f}")



# 1) Design model( input, output size, forward pass)     
# 2) Construct loss and optimizer.       l=((y_predicted - y)**2).mean()
# 3) Training loop
#     - Forward pass: compute prediction.   w * x        :Loss
#     - Backward pass: gardient     l.backward
#     - Update the weigths ( keep going in a loop untill the loss is minimized).    w - =lr *w.grad --> Optimizer 

using sklearn

In [ ]:
import torch 
import torch.nn as nn 
import numpy as np
from sklearn import datasets 
import matplotlib.pyplot as plt

# prepare data 
X_numpy, y_numpy = datasets.make_regression(n_samples= 100, n_features=1, noise=20, random_state= 1)

#print(X_numpy,y_numpy)

X = torch.from_numpy(X_numpy.astype(np.float32))

y = torch.from_numpy(y_numpy.astype(np.float32))

y= y.view(-1 ,1 )


n_samples, n_features = X.shape

# model
input_size = n_features
output_size = n_features

model = nn.Linear(input_size, output_size)


#loss function 
learning_rate = 0.01
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)


#training loop

num_epochs = 500 

for epoch in range(num_epochs):
  #prediction = forward pass
  y_pred = model(X)
  #loss
  loss = criterion( y_pred, y)

  #gradients = backward pass
  loss.backward() #loss with respect to w --> dl/dw

  #update weights
  optimizer.step()
  #zero gradients
  optimizer.zero_grad()

  if (epoch+1) % 10 == 0:
    print(f'epoch {epoch+1}: loss =  {loss.item():.8f}')

 #plot 
predicted = model(X).detach().numpy()

plt.plot(X_numpy,y_numpy,"ro")

plt.plot(X_numpy, predicted, "b")

plt.show()
   

#Logistic Regression 

In [28]:
import torch 
import torch.nn as nn 
import numpy as np
from sklearn import datasets 
from sklearn.preprocessing import StandardScaler # 
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [48]:
bc = datasets.load_breast_cancer()

X,y = bc.data, bc.target

n_samples,n_features = X.shape

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size = 0.2, random_state = 1234)

#scale

sc = StandardScaler() #recommend to do 

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


X_train = torch.from_numpy(X_train.astype(np.float32))

X_test = torch.from_numpy(X_test.astype(np.float32))

y_train = torch.from_numpy(y_train.astype(np.float32))

y_test = torch.from_numpy(y_test.astype(np.float32))


#reshape 

y_train = y_train.view(-1,1)
y_test = y_test.view(-1,1)

#model 

class LogisticRegression(nn.Module):
  def __init__(self,n_inputs_features):
    super(LogisticRegression,self).__init__()
    self.linear = nn.Linear(n_inputs_features, 1)

  def forward(self, x):
    y_predicted = torch.sigmoid(self.linear(x))
    return y_predicted 

model = LogisticRegression(n_features)    



# loss and optimizer 
learning_rate = 0.01
criterion = nn.BCELoss() # binary cross entopy 
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
# training loop

num_epochs = 30000

for epoch in range(num_epochs):
  #prediction = forward pass
  y_predicted = model(X_train)
  #loss
  loss = criterion( y_predicted, y_train)

  #gradients = backward pass
  loss.backward() #loss with respect to w --> dl/dw

  #update weights
  optimizer.step()
  #zero gradients
  optimizer.zero_grad()

  if (epoch+1) % 10000 == 0:
    print(f'epoch {epoch+1}: loss =  {loss.item():.8f}')

#evaluation 
with torch.no_grad():
  y_predicted = model(X_test)
  y_predicted_cls = y_predicted.round()  
  acc = y_predicted_cls.eq(y_test).sum()/float(y_test.shape[0])  
  print (f"accuray = {acc:4f}")

epoch 10000: loss =  0.04072985
epoch 20000: loss =  0.03326616
epoch 30000: loss =  0.02980602
accuray = 0.956140


#dataset and data loader 