<a href="https://colab.research.google.com/github/avinashronanki/pytorch/blob/master/pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 
x = torch.rand(3)
print(x)

In [ ]:
torch.cuda.is_available().  # to check if gpu is connected or not 

In [ ]:
empty = torch.empty(3) # un intialized memory /data 
print(empty)

In [ ]:
zero = torch.zeros(3)
print(zero)

In [ ]:
empty + one

In [ ]:
one = torch.ones(3)
print(one)

create 2d 3d and 4d tensor 

In [17]:
twod = torch.rand(2,2)
threed = torch.rand(2,2,2)
fourd = torch.rand(2,2,2,2)

In [24]:
c  = torch.ones(2,2, dtype =torch.float) # mention date type 

list 

In [23]:
l = torch.ones([1,2])

Adding two tensors 

In [27]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z= x+y   
print(z)

z = torch.add(x,y) # add function 


tensor([[0.8325, 1.3713],
        [0.8632, 0.8652]])


In [28]:
print(y)

tensor([[0.6337, 0.7274],
        [0.4152, 0.3477]])


modify the variable with addition 

In [29]:
y.add_(x)
print(y)

tensor([[0.8325, 1.3713],
        [0.8632, 0.8652]])


substraction 

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z= x-y   
print(z)

z = torch.sub(x,y) # substraction function 

divison 

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z= x/ y   
print(z)

z = torch.div(x,y) # division  function 

Slice

In [31]:
a = torch.rand(5,4)

In [36]:
print(a)

tensor([[0.9725, 0.8286, 0.1985, 0.6716],
        [0.5158, 0.3561, 0.6893, 0.1104],
        [0.8168, 0.3879, 0.8921, 0.6888],
        [0.7019, 0.3297, 0.7578, 0.1883],
        [0.5933, 0.2272, 0.2099, 0.8052]])


In [ ]:
print(a[1:3,:])

In [ ]:
print(a[[2,4],:])

In [37]:
a[1,1] # taking a specific postion 

tensor(0.3561)

In [38]:
a[1,1].item()   # if you need the value of the tensor 

0.3561347723007202

REshape 

In [44]:
r = torch.rand(6,6)
print (r)
y = r.view(36) # in a single list 
print(y)

tensor([[0.9520, 0.2428, 0.4987, 0.7993, 0.8776, 0.7078],
        [0.9136, 0.2007, 0.8112, 0.7529, 0.3412, 0.7893],
        [0.9817, 0.1569, 0.0114, 0.0199, 0.5911, 0.3896],
        [0.7242, 0.4373, 0.9833, 0.1772, 0.8281, 0.1766],
        [0.5861, 0.9514, 0.2313, 0.0517, 0.6457, 0.7085],
        [0.0889, 0.1592, 0.9855, 0.2104, 0.8430, 0.4124]])
tensor([0.9520, 0.2428, 0.4987, 0.7993, 0.8776, 0.7078, 0.9136, 0.2007, 0.8112,
        0.7529, 0.3412, 0.7893, 0.9817, 0.1569, 0.0114, 0.0199, 0.5911, 0.3896,
        0.7242, 0.4373, 0.9833, 0.1772, 0.8281, 0.1766, 0.5861, 0.9514, 0.2313,
        0.0517, 0.6457, 0.7085, 0.0889, 0.1592, 0.9855, 0.2104, 0.8430, 0.4124])


In [ ]:
# convert into 8 column metric 

y = r.view(-1, 9)
print(y)

In [ ]:
z = r.view(2, -1)
print(z.size())

In [ ]:
z.view(-1)

numpy array 

In [55]:
import numpy as np
 
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [56]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [58]:
# numpy to tensor 

n = np.ones(5)
print(n)
t = torch.from_numpy(n)
print(t)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [59]:
n += 1
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


cuda 

In [60]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device= device)
  y = torch.ones(5)
  y = y.to(device) # converting into cuda 
  z= x+y 

  print(z)


tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [61]:
# moving it back to cpu version 
z= z.to("cpu") # important 


Gradients calculation with Autogred 

In [62]:
g = torch.ones(5, requires_grad=True)
print(g)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [79]:
x = torch.rand(3,3, requires_grad=True)
print(x)

y = x+2
print (y) #  grad_fn=<AddBackward0> 

tensor([[0.4301, 0.7209, 0.7149],
        [0.2627, 0.6174, 0.3840],
        [0.8414, 0.7427, 0.7175]], requires_grad=True)
tensor([[2.4301, 2.7209, 2.7149],
        [2.2627, 2.6174, 2.3840],
        [2.8414, 2.7427, 2.7175]], grad_fn=<AddBackward0>)


In [80]:
z = y*y*2

print (z) #grad_fn=<MulBackward0>)

tensor([[11.8104, 14.8063, 14.7417],
        [10.2396, 13.7019, 11.3670],
        [16.1467, 15.0444, 14.7700]], grad_fn=<MulBackward0>)


In [81]:
z = z.mean()
print(z) # grad_fn=<MeanBackward0>)

tensor(13.6253, grad_fn=<MeanBackward0>)


In [82]:
# backward pass 
z.backward() # dz/dx
print (x.grad)

tensor([[1.0800, 1.2093, 1.2066],
        [1.0056, 1.1633, 1.0596],
        [1.2628, 1.2190, 1.2078]])


In [ ]:
# with out disturbing the gradents perfroming some operation on x 
x = torch.rand(3, requires_grad=True)
print(x)
x.requires_grad(False)
x.detach()
with torch.no_grad()

y = X+2 
print (y)

Neural network with weights 

In [86]:
import torch 

weights = torch.ones(4, requires_grad=True)
print(weights)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()
  print(model_output)

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)


optimizer SGD

In [ ]:
import torch 

weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr= 0.01)
optimizer.step()
optimizer.zero_grad()

Backpropagation 
1. forward pass (loss)
2.local gradients 
3.backword propagation loss 

In [92]:
# chain rule 
# computational graph 

#linear regression 


import torch 

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w= torch.tensor(1.0, requires_grad=True)

#forword pass and compute loss

y_hat = w * x
loss =(y_hat - y)**2

print(loss)

#backword pass 
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


Gradient Descent With Autograd and Backpropagation 



In [ ]:
prediction : pytoch model 
GD : Auto grad 
Loss Computation : loss function 
parameter : optimizer 

In [96]:
#linear Regression 

X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)
w=0.0


#model prediction 
def forward(x):
  return w * x


#loss =MSE
def loss(y, y_predicted):
  return ((y_predicted - y)**2).mean()


#gardient
#MSE = 1/N * (w*x -y) **2
#d/dw =1/N 2x (w*x -y)
def gradient( x, y, y_predicted):
  return np.dot(2*x, y_predicted -y).mean()

print("Prediction before training: f(5) = {forward(5):.3f}")

#training
learning_rate = 0.01
n_iters = 20


for epoch in range(n_iters):
  #prediction = forward pass
  y_pred = forward(X)

  #loss
  l = loss( Y, y_pred)


  #gradients
  dw = gradient( X, Y, y_pred)


 #update weights
  w -=learning_rate * dw

  if epoch % 2 == 0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss {l:.8f}')

print(f"Prediction after training: f(5) = {forward(5):.3f}")

Prediction before training: f(5) = {forward(5):.3f}
epoch 1: w = 1.200, loss 30.00000000
epoch 3: w = 1.872, loss 0.76800019
epoch 5: w = 1.980, loss 0.01966083
epoch 7: w = 1.997, loss 0.00050331
epoch 9: w = 1.999, loss 0.00001288
epoch 11: w = 2.000, loss 0.00000033
epoch 13: w = 2.000, loss 0.00000001
epoch 15: w = 2.000, loss 0.00000000
epoch 17: w = 2.000, loss 0.00000000
epoch 19: w = 2.000, loss 0.00000000
Prediction after training: f(5) = 10.000


Liner regression with pytorch